[2021-01-11T05:10:06.009735+01:00] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_route":"admin","_controller":"App\\Controller\\Admin\\DashboardController::index"},"request_uri":"http://localhost:8000/admin","method":"GET"} []
[2021-01-11T05:10:06.011401+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-01-11T05:10:06.011411+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-01-11T05:10:06.011417+01:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-01-11T05:10:06.011850+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken"} []
[2021-01-11T05:10:06.021483+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"okok@gmail.com"} []
[2021-01-11T05:10:06.021844+01:00] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/souaguen/Bureau/s2ipartner/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-01-11T05:10:06.034224+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /home/souaguen/Bureau/s2ipartner/vendor/symfony/security-http/Firewall/ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /home/souaguen/Bureau/s2ipartner/vendor/symfony/security-http/Firewall/ExceptionListener.php:137)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/souaguen/Bureau/s2ipartner/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-01-11T05:10:06.067978+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-01-11T05:10:17.495834+01:00] request.INFO: Matched route "client". {"route":"client","route_parameters":{"_route":"client","_controller":"App\\Controller\\ClientController::client"},"request_uri":"http://localhost:8000/client","method":"POST"} []
[2021-01-11T05:10:17.507851+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken"} []
[2021-01-11T05:10:17.529543+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"okok@gmail.com"} []
[2021-01-11T05:10:17.529570+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-01-11T05:10:17.529576+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-01-11T05:10:17.529683+01:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-01-11T05:10:18.006394+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO client (society, firstname, lastname, phone, email, poste, valid, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["OkSociety", "Okok", "OkOk", "0102030405", "okok@gmail.com", "Developpeur", 0, 5]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395'" at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 74 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO client (society, firstname, lastname, phone, email, poste, valid, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [\"OkSociety\", \"Okok\", \"OkOk\", \"0102030405\", \"okok@gmail.com\", \"Developpeur\", 0, 5]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395' at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:74)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395' at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395' at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)"} []
[2021-01-11T05:10:18.008694+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-01-11T05:10:50.162316+01:00] request.INFO: Matched route "client". {"route":"client","route_parameters":{"_route":"client","_controller":"App\\Controller\\ClientController::client"},"request_uri":"http://localhost:8000/client","method":"POST"} []
[2021-01-11T05:10:50.163720+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken"} []
[2021-01-11T05:10:50.174239+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"okok@gmail.com"} []
[2021-01-11T05:10:50.174260+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-01-11T05:10:50.174264+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-01-11T05:10:50.174330+01:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-01-11T05:10:50.201228+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO client (society, firstname, lastname, phone, email, poste, valid, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["OkSociety", "Okok", "OkOk", "0102030405", "okok@gmail.com", "Developpeur", 0, 5]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395'" at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 74 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO client (society, firstname, lastname, phone, email, poste, valid, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [\"OkSociety\", \"Okok\", \"OkOk\", \"0102030405\", \"okok@gmail.com\", \"Developpeur\", 0, 5]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395' at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:74)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395' at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'client.UNIQ_C7440455A76ED395' at /home/souaguen/Bureau/s2ipartner/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)"} []
[2021-01-11T05:10:50.204513+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
